import {
  ActivitySquare,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  BatteryCharging,
  Bell,
  Bot,
  Brain,
  Bug,
  Check,
  ChevronDown,
  ChevronRight,
  CircleDot,
  Clock,
  Cloud,
  CloudCog,
  Code,
  Code2,
  Cpu,
  Database,
  Download,
  ExternalLink,
  FileCode,
  FileJson,
  FileText,
  FileCsv,
  FilePdf,
  Flow,
  FolderOpen,
  Github,
  HardDrive,
  History,
  Languages,
  Layout,
  Layers,
  Link2,
  Loader,
  LogOut,
  Menu,
  MessageSquare,
  Monitor,
  Network,
  PackageCheck,
  RefreshCw,
  SaveAll,
  ScrollText,
  Settings,
  Share2,
  Star,
  Terminal,
  Timer,
  Type,
  Upload,
  User,
  UserCircle,
  Wand2,
  Wifi,
  X,
  type LucideIcon,
} from 'lucide-react';

// Map framework/technology names to icons
export const FrameworkIcons: Record<string, LucideIcon> = {
  angular: Code2,
  astro: Star,
  react: Code2,
  vue: Code2,
  svelte: Code2,
  nextjs: Layout,
  nuxt: Layout,
  remix: FileCode,
  typescript: Type,
  vite: Wand2,
};

// Export commonly used icons
export const Icons = {
  close: X,
  menu: Menu,
  settings: Settings,
  chat: MessageSquare,
  terminal: Terminal,
  github: Github,
  loader: Loader,
  cpu: Cpu,
  logout: LogOut,
  user: User,
  save: SaveAll,
  folderOpen: FolderOpen,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  check: Check,
  alert: AlertTriangle,
  archive: Archive,
  download: ArrowDownToLine,
  battery: BatteryCharging,
  clock: Clock,
  cloudSettings: CloudCog,
  code: Code,
  download: Download,
  externalLink: ExternalLink,
  fileJson: FileJson,
  fileText: FileText,
  fileCsv: FileCsv,
  filePdf: FilePdf,
  flow: Flow,
  hardDrive: HardDrive,
  language: Languages,
  layers: Layers,
  link: Link2,
  monitor: Monitor,
  network: Network,
  package: PackageCheck,
  scroll: ScrollText,
  share: Share2,
  timer: Timer,
  upload: Upload,
  userCircle: UserCircle,
  wifi: Wifi,
  alert: AlertCircle,
  activity: ActivitySquare,
  circleDot: CircleDot,
};

// Helper for dynamic framework icon lookup
export const getFrameworkIcon = (framework: string): LucideIcon => {
  return FrameworkIcons[framework.toLowerCase()] || Code2;
};
